import { Property, ChatThread, User } from './types';

export const DEMO_OWNER: User = {
  id: 'owner-1',
  role: 'owner',
  name: 'আব্দুল করিম',
  email: 'karim@example.com',
  phone: '01712345678',
  whatsapp: '01712345678',
  division: 'dhaka',
  district: 'dhaka-city',
  upazila: 'uttara',
  kycVerified: true,
  createdAt: '2024-01-15',
};

export const SAMPLE_PROPERTIES: Property[] = [
  {
    id: 'prop-1',
    ownerId: 'owner-1',
    ownerName: 'আব্দুল করিম',
    ownerPhone: '01712345678',
    title: '৩ বেডরুম ফার্নিশড ফ্ল্যাট - উত্তরা',
    type: 'apartment',
    description: 'উত্তরা সেক্টর ৭ এ সুন্দর ৩ বেডরুমের ফ্ল্যাট ভাড়া দেওয়া হবে। সম্পূর্ণ ফার্নিশড, লিফট ও জেনারেটর সুবিধা আছে। কাছেই স্কুল, মসজিদ ও মার্কেট।',
    images: [],
    division: 'ঢাকা',
    district: 'ঢাকা',
    upazila: 'উত্তরা',
    address: 'সেক্টর ৭, রোড ১২, উত্তরা, ঢাকা',
    rent: 25000,
    deposit: 50000,
    serviceCharge: 3000,
    bedrooms: 3,
    bathrooms: 2,
    floorLevel: 5,
    totalFloors: 8,
    area: 1200,
    furnishing: 'furnished',
    genderPreference: 'family',
    parking: true,
    gasConnection: true,
    waterSupply: true,
    elevator: true,
    generator: true,
    security: true,
    negotiable: true,
    available: true,
    verified: true,
    featured: true,
    views: 245,
    createdAt: '2025-02-01',
  },
  {
    id: 'prop-2',
    ownerId: 'owner-2',
    ownerName: 'ফাতেমা বেগম',
    ownerPhone: '01812345678',
    title: '২ বেডরুম ফ্ল্যাট - ধানমন্ডি',
    type: 'apartment',
    description: 'ধানমন্ডি ২৭ নম্বরে ২ বেডরুমের সুন্দর ফ্ল্যাট। কাছেই ধানমন্ডি লেক ও স্টার কবির মার্কেট।',
    images: [],
    division: 'ঢাকা',
    district: 'ঢাকা',
    upazila: 'ধানমন্ডি',
    address: '২৭ নম্বর, ধানমন্ডি, ঢাকা',
    rent: 18000,
    deposit: 36000,
    serviceCharge: 2500,
    bedrooms: 2,
    bathrooms: 2,
    floorLevel: 3,
    totalFloors: 6,
    area: 950,
    furnishing: 'semi-furnished',
    genderPreference: 'family',
    parking: false,
    gasConnection: true,
    waterSupply: true,
    elevator: true,
    generator: false,
    security: true,
    negotiable: true,
    available: true,
    verified: true,
    featured: true,
    views: 189,
    createdAt: '2025-02-05',
  },
  {
    id: 'prop-3',
    ownerId: 'owner-3',
    ownerName: 'রহিম উদ্দিন',
    ownerPhone: '01912345678',
    title: 'সাবলেট - বনানী',
    type: 'sublet',
    description: 'বনানী ১১ নম্বরে ১ রুম সাবলেট দেওয়া হবে। ব্যাচেলরদের জন্য উপযুক্ত। Wi-Fi ও গ্যাস সুবিধা আছে।',
    images: [],
    division: 'ঢাকা',
    district: 'ঢাকা',
    upazila: 'বনানী',
    address: '১১ নম্বর, বনানী, ঢাকা',
    rent: 7000,
    deposit: 14000,
    serviceCharge: 1000,
    bedrooms: 1,
    bathrooms: 1,
    floorLevel: 4,
    totalFloors: 7,
    area: 350,
    furnishing: 'furnished',
    genderPreference: 'male',
    parking: false,
    gasConnection: true,
    waterSupply: true,
    elevator: true,
    generator: false,
    security: false,
    negotiable: false,
    available: true,
    verified: false,
    featured: false,
    views: 78,
    createdAt: '2025-02-10',
  },
  {
    id: 'prop-4',
    ownerId: 'owner-1',
    ownerName: 'আব্দুল করিম',
    ownerPhone: '01712345678',
    title: '৪ বেডরুম বাড়ি - গুলশান',
    type: 'house',
    description: 'গুলশান ২ এ ৪ বেডরুমের স্বতন্ত্র বাড়ি। বড় বাগান, গ্যারেজ ও ড্রাইভার রুম সহ। এম্বাসি এলাকায় অবস্থিত।',
    images: [],
    division: 'ঢাকা',
    district: 'ঢাকা',
    upazila: 'গুলশান',
    address: 'গুলশান ২, রোড ৪৫, ঢাকা',
    rent: 65000,
    deposit: 130000,
    serviceCharge: 8000,
    bedrooms: 4,
    bathrooms: 3,
    floorLevel: 1,
    totalFloors: 3,
    area: 2500,
    furnishing: 'unfurnished',
    genderPreference: 'family',
    parking: true,
    gasConnection: true,
    waterSupply: true,
    elevator: false,
    generator: true,
    security: true,
    negotiable: true,
    available: true,
    verified: true,
    featured: true,
    views: 412,
    createdAt: '2025-01-20',
  },
  {
    id: 'prop-5',
    ownerId: 'owner-4',
    ownerName: 'নাসরিন আক্তার',
    ownerPhone: '01612345678',
    title: 'অফিস স্পেস - মতিঝিল',
    type: 'office',
    description: 'মতিঝিল বাণিজ্যিক এলাকায় আধুনিক অফিস স্পেস। এসি, ইন্টারনেট ও সার্ভিস সুবিধা সহ।',
    images: [],
    division: 'ঢাকা',
    district: 'ঢাকা',
    upazila: 'মতিঝিল',
    address: 'মতিঝিল বা/এ, দিলকুশা, ঢাকা',
    rent: 45000,
    deposit: 90000,
    serviceCharge: 5000,
    bedrooms: 0,
    bathrooms: 2,
    floorLevel: 8,
    totalFloors: 12,
    area: 1800,
    furnishing: 'furnished',
    genderPreference: 'any',
    parking: true,
    gasConnection: false,
    waterSupply: true,
    elevator: true,
    generator: true,
    security: true,
    negotiable: true,
    available: true,
    verified: true,
    featured: false,
    views: 156,
    createdAt: '2025-02-08',
  },
  {
    id: 'prop-6',
    ownerId: 'owner-5',
    ownerName: 'মোহাম্মদ হাসান',
    ownerPhone: '01512345678',
    title: 'মেস সিট - মিরপুর',
    type: 'mess',
    description: 'মিরপুর ১০ নম্বরে মেস সিট খালি আছে। ছাত্রদের জন্য উপযুক্ত। ৩ বেলা খাবার সুবিধা আছে।',
    images: [],
    division: 'ঢাকা',
    district: 'ঢাকা',
    upazila: 'মিরপুর',
    address: 'মিরপুর ১০, ঢাকা',
    rent: 4500,
    deposit: 4500,
    serviceCharge: 0,
    bedrooms: 1,
    bathrooms: 1,
    floorLevel: 3,
    totalFloors: 5,
    area: 120,
    furnishing: 'furnished',
    genderPreference: 'male',
    parking: false,
    gasConnection: true,
    waterSupply: true,
    elevator: false,
    generator: false,
    security: false,
    negotiable: false,
    available: true,
    verified: false,
    featured: false,
    views: 92,
    createdAt: '2025-02-12',
  },
  {
    id: 'prop-7',
    ownerId: 'owner-2',
    ownerName: 'ফাতেমা বেগম',
    ownerPhone: '01812345678',
    title: '৩ বেডরুম ফ্ল্যাট - বসুন্ধরা',
    type: 'apartment',
    description: 'বসুন্ধরা আবাসিক এলাকায় ৩ বেডরুমের নতুন ফ্ল্যাট। কমিউনিটি সেন্টার, পার্ক ও মসজিদ কাছে।',
    images: [],
    division: 'ঢাকা',
    district: 'ঢাকা',
    upazila: 'বসুন্ধরা',
    address: 'ব্লক ডি, বসুন্ধরা আ/এ, ঢাকা',
    rent: 22000,
    deposit: 44000,
    serviceCharge: 3500,
    bedrooms: 3,
    bathrooms: 2,
    floorLevel: 6,
    totalFloors: 10,
    area: 1100,
    furnishing: 'semi-furnished',
    genderPreference: 'family',
    parking: true,
    gasConnection: true,
    waterSupply: true,
    elevator: true,
    generator: true,
    security: true,
    negotiable: false,
    available: true,
    verified: true,
    featured: false,
    views: 167,
    createdAt: '2025-02-03',
  },
  {
    id: 'prop-8',
    ownerId: 'owner-6',
    ownerName: 'জহিরুল ইসলাম',
    ownerPhone: '01412345678',
    title: 'দোকান - মোহাম্মদপুর',
    type: 'shop',
    description: 'মোহাম্মদপুর টাউন হলের কাছে রাস্তার পাশে দোকান ভাড়া দেওয়া হবে। ব্যবসার জন্য উত্তম স্থান।',
    images: [],
    division: 'ঢাকা',
    district: 'ঢাকা',
    upazila: 'মোহাম্মদপুর',
    address: 'টাউন হল রোড, মোহাম্মদপুর, ঢাকা',
    rent: 30000,
    deposit: 60000,
    serviceCharge: 2000,
    bedrooms: 0,
    bathrooms: 1,
    floorLevel: 1,
    totalFloors: 1,
    area: 400,
    furnishing: 'unfurnished',
    genderPreference: 'any',
    parking: false,
    gasConnection: false,
    waterSupply: true,
    elevator: false,
    generator: false,
    security: true,
    negotiable: true,
    available: true,
    verified: false,
    featured: false,
    views: 65,
    createdAt: '2025-02-14',
  },
];

export const SAMPLE_CHATS: ChatThread[] = [
  {
    id: 'chat-1',
    participantIds: ['client-1', 'owner-1'],
    participantNames: ['আপনি', 'আব্দুল করিম'],
    propertyId: 'prop-1',
    propertyTitle: '৩ বেডরুম ফার্নিশড ফ্ল্যাট - উত্তরা',
    lastMessage: 'ভাই, ফ্ল্যাটটি কি এখনও খালি আছে?',
    lastMessageTime: '2025-02-18T10:30:00',
    unreadCount: 2,
  },
  {
    id: 'chat-2',
    participantIds: ['client-1', 'owner-2'],
    participantNames: ['আপনি', 'ফাতেমা বেগম'],
    propertyId: 'prop-2',
    propertyTitle: '২ বেডরুম ফ্ল্যাট - ধানমন্ডি',
    lastMessage: 'জি, আপনি দেখে যেতে পারেন।',
    lastMessageTime: '2025-02-17T14:20:00',
    unreadCount: 0,
  },
];
